export const apis = {
    'user.user': '/user/user/',
    'oauth2.token': '/oauth2/token/',
    'product.customer.list': '/product/new/customer/list/',
    // 'product.customer.list': '/product/customer/list/',
    'category.list': '/product/category/list/',
    'product.recommended.list': '/product/recommended/list/',
    'product.recommended.create': '/product/recommended/create/',
    'product.selected.list': '/product/selected/list/',
    'product.brand.list': '/product/brand/list/',
    'product.topic.list': '/product/topic/list/',
    'promotion.cut.list': '/promotion/cut/list/',
    'product.topic.products': '/product/topic/products/',
    'address.state.list': '/address/state/list/',
    'address.shipping.list': '/address/shipping/list/',
    'order.cut.create': '/order/cut/create/',
    'order.customer.list': '/order/customer/list/',
    'image.qiniu': '/image/qiniu/',
    'promotion.banner.list': '/promotion/banner/list/',
    'user.userprofile': '/user/userprofile/',
    'user.google.sign': '/user/google_sign/',
    'user.logout': '/oauth2/revoke_token/',
    'promotion.cut.create': '/promotion/cut/create/',
    'promotion.get.list': '/promotion/get/list/',
    'get.card': '/point/voucher/list/',
    'point.exchange': '/point/exchange/voucher/',
    'point.detail': '/point/point/detail/',
    'address.get.default': '/address/get/default/',
    'notice.list': '/notice/list/ ',
    'notice.detail': '/notice/detail/',
    'app.get.version': '/app/get/version/',
    'order.create': '/order/create/',
    'product.cut.list': '/product/cut/list/', // 砍价商品的列表
    'promotion.new.cut.list': '/promotion/new/cut/list/', // 我的砍价列表
    'payment.razorpay.check': '/payment/razorpay/check/',
    'order.create.payment': '/order/create/payment/',
    'order.cut.create.payment': '/order/cut/create/payment/',
    'order.create.pure': '/order/create/pure/',
    'order.cut.create.pure': '/order/cut/create/pure/',
    'payment.paytm.checksum': '/payment/paytm/checksum/',
    'payment.paytm.get.status': '/payment/paytm/get/status/',
    'payment.razorpay.create': '/payment/razorpay/create/',
    'order.flash.pure': '/order/flash/pure/',
    'flashsale.flash.customer.home': '/flashsale/flash/customer/home/'
}
