export const apis = {
    'user.user': '/user/user/',
    'oauth2.token': '/oauth2/token/',
    'product.customer.list': '/product/new/customer/list/',
    'category.list': '/product/category/list/',
    'product.recommended.list': '/product/recommended/list/',
    'product.recommended.create': '/product/recommended/create/',
    'product.selected.list': '/product/selected/list/',
    'product.brand.list': '/product/brand/list/',
    'product.topic.list': '/product/topic/list/',
    'promotion.cut.list': '/promotion/cut/list/',
    'product.topic.products': '/product/topic/products/',
    'address.state.list': '/address/state/list/',
    'address.shipping.list': '/address/shipping/list/',
    'order.cut.create': '/order/cut/create/',
    'order.customer.list': '/order/customer/list/',
    'image.qiniu': '/image/qiniu/',
    'promotion.banner.list': '/promotion/banner/list/',
    'user.userprofile': '/user/userprofile/',
    'user.google.sign': '/user/google_sign/',
    'user.logout': '/oauth2/revoke_token/',
    'promotion.cut.create': '/promotion/cut/create/',
    'promotion.get.list': '/promotion/get/list/',
    'get.card': '/point/voucher/list/',
    'point.exchange': '/point/exchange/voucher/',
    'point.detail': '/point/point/detail/',
    'address.get.default': '/address/get/default/',
    'notice.list': '/notice/list/ ',
    'notice.detail': '/notice/detail/',
    'app.get.version': '/app/get/version/',
    'order.create': '/order/create/'
}
