export const tabConfig = [{
    icon: '&#xe73c;',
    name: 'Home',
    key: 'home',
    src: `${weex.config.eros.jsServer}/dist/js/pages/mobile/home/index.js`,
    visibility: 'visible'
}, {
    icon: '&#xe6f8;',
    name: 'Drops',
    key: 'drops',
    src: `${weex.config.eros.jsServer}/dist/js/pages/mobile/drops/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe74a;',
    name: 'Luckydraw',
    key: 'luckydraw',
    redPoint: true,
    src: `${weex.config.eros.jsServer}/dist/js/pages/mobile/raffle/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe733;',
    name: 'Perks',
    key: 'perks',
    src: `${weex.config.eros.jsServer}/dist/js/pages/mobile/perks/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe701;',
    name: 'Account',
    key: 'account',
    src: `${weex.config.eros.jsServer}/dist/js/pages/mobile/my/index.js`,
    visibility: 'hidden'
}];
